### ISSUE TITLE
time series data like BTC price

### ISSUE THREAD

**Issue by tesla-cat** [karpathy/ng-video-lecture#14]
if we have a time series data like BTC price, then we don't need to do `token_embedding` i suppose,

how do we do `position_embedding` in this case?

**Comment by mynkpl1998** [comment]
The paper "Attention is all you need", used the below encoding. Take a look, might be useful for you time series. 

Paper link:  https://arxiv.org/pdf/1706.03762.pdf
Section: 3.5 Positional Encoding

<img width="267" alt="image" src="https://user-images.githubusercontent.com/15110441/236662000-99a75ce7-8272-44d0-bda1-97a95dea1945.png">
