### ISSUE TITLE
Shouldn't we be dividing when normalizing QK^T, not multiplying?

### ISSUE THREAD

**Issue by tylerkastner** [karpathy/ng-video-lecture#46]
In the code below, the query-key dot product is normalized by multiplying by the square root of the head size:
https://github.com/karpathy/ng-video-lecture/blob/52201428ed7b46804849dea0b3ccf0de9df1a5c3/gpt.py#L83
Should we not be dividing instead? As seen in the original paper:
<img width="294" alt="Screenshot 2024-09-19 at 2 26 20 PM" src="https://github.com/user-attachments/assets/ff55962c-364e-4d6e-a6c7-d2d8fe09dcb3">

**Comment by rishabhjain1198** [comment]
It's raising to the power of `-0.5`, so it's effectively dividing it.

**Comment by tylerkastner** [comment]
Of course! I missed that minus. Thanks for spotting that 🤦
